#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file for the TEST environment.
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

// Use the test database
$config['components']['db'] = require __DIR__ . '/config/test_db.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);